apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.2xlarge"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand","spot"]
  provider:
    subnetSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
    securityGroupSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  ttlSecondsAfterEmpty: 3
  limits:
    resources:
      cpu: "2000"
  labels:
    billing-team: my-team     
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: manual-1
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.large"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  provider:
    subnetSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
    securityGroupSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  ttlSecondsAfterEmpty: 3
  limits:
    resources:
      cpu: "2000"
  labels:
    billing-team: my-team     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manual-1
  template:
    metadata:
      labels:
        app: manual-1
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: manual-1
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: manual-1
        resources:
          requests:
            cpu: "125m"
            memory: 128M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manual-2
  template:
    metadata:
      labels:
        app: manual-2
    spec:
      nodeSelector:
        karpenter.sh/capacity-type: spot
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: manual-2
        resources:
          requests:
            cpu: "125m"
            memory: 128M
