apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default_1
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.small", "t3.medium", "t3.large"]
    - key: "topology.kubernetes.io/zone" 
      operator: In
      values: ["us-east-1a", "us-east-1c", "us-east-1c"]
  provider:
    subnetSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
    securityGroupSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  ttlSecondsAfterEmpty: 3
  limits:
    resources:
      cpu: "1000"
  labels:
    billing-team: my-team     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      # nodeSelector:
      #   billing-team: my-team
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: default
        resources:
          requests:
            cpu: "1"
            memory: 256M
