apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-3
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.small", "t3.medium", "t3.large","t3.2xlarge","m5.large", "m5.2xlarge"]
    - key: "topology.kubernetes.io/zone" 
      operator: In
      values: ["us-east-1a", "us-east-1c", "us-east-1c"]
  provider:
    subnetSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
    securityGroupSelector:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: "2000"
  labels:
    billing-team: my-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consolidation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consolidation
  template:
    metadata:
      labels:
        app: consolidation
    spec:
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: consolidation
        resources:
          requests:
            cpu: "1"
            memory: 256M
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: consolidation
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
