apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-demo
  region: us-west-2

managedNodeGroups:
- name: l-group
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true
  spot: false
- name: l-spot-group
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true
  spot: true
- name: my-spot-managed-node-group
  desiredCapacity: 2
  spot: true
  instanceSelector:
    vCPUs: 2
    memory: 2GiB
    cpuArchitecture: x86_64